"""Gettext bo‘lmasa ham ishlaydigan UI qatorlari (en / uz / ru)."""

from django.utils.translation import get_language

_TEXTS: dict[str, dict[str, str]] = {
    "en": {
        "resume": "Resume",
        "language": "Language",
        "about_me": "About me",
        "certificates": "Certificates",
        "interests": "Interests",
        "website": "Website",
        "view_document": "View document",
        "built_with_django": "Built with Django",
        "nav_hero": "Home",
        "nav_about": "About",
        "nav_experience": "Experience",
        "nav_education": "Education",
        "nav_certificates": "Certificates",
        "nav_interests": "Interests",
        "nav_contact": "Contact",
        "skills": "Skills",
        "experience": "Experience",
        "education": "Education",
        "contact": "Contact",
        "get_in_touch": "Get in touch",
        "contact_lead": "Open to opportunities and collaborations.",
        "cta_resume": "Contact",
        "period_present": "Present",
        "document": "Document",
        "admin_title": "CV resume administration",
        "admin_site": "CV Admin",
        "admin_dashboard": "Dashboard",
        "cv_content_lang": "CV content language",
        "cv_content_lang_hint": "Fields below show text for the selected language only. Switch language, then Save.",
    },
    "uz": {
        "resume": "Rezyume",
        "language": "Til",
        "about_me": "O‘zim haqimda",
        "certificates": "Sertifikatlar",
        "interests": "Qiziqishlar",
        "website": "Veb-sayt",
        "view_document": "Hujjatni ko‘rish",
        "built_with_django": "Django yordamida yig‘ilgan",
        "nav_hero": "Bosh",
        "nav_about": "Men haqimda",
        "nav_experience": "Tajriba",
        "nav_education": "Ta’lim",
        "nav_certificates": "Sertifikatlar",
        "nav_interests": "Qiziqishlar",
        "nav_contact": "Aloqa",
        "skills": "Ko‘nikmalar",
        "experience": "Tajriba",
        "education": "Ta’lim",
        "contact": "Aloqa",
        "get_in_touch": "Bog‘lanish",
        "contact_lead": "Taklif va hamkorlik uchun ochiqman.",
        "cta_resume": "Aloqa",
        "period_present": "Hozirgi vaqt",
        "document": "Hujjat",
        "admin_title": "CV rezyume boshqaruvi",
        "admin_site": "CV admin",
        "admin_dashboard": "Boshqaruv paneli",
        "cv_content_lang": "CV matni tili",
        "cv_content_lang_hint": "Quyidagi maydonlar faqat tanlangan til uchun. Tilni almashtiring, keyin Saqlash.",
    },
    "ru": {
        "resume": "Резюме",
        "language": "Язык",
        "about_me": "Обо мне",
        "certificates": "Сертификаты",
        "interests": "Интересы",
        "website": "Сайт",
        "view_document": "Открыть документ",
        "built_with_django": "Сделано на Django",
        "nav_hero": "Главная",
        "nav_about": "Обо мне",
        "nav_experience": "Опыт",
        "nav_education": "Образование",
        "nav_certificates": "Сертификаты",
        "nav_interests": "Интересы",
        "nav_contact": "Контакты",
        "skills": "Навыки",
        "experience": "Опыт",
        "education": "Образование",
        "contact": "Контакты",
        "get_in_touch": "Связаться",
        "contact_lead": "Открыт к предложениям и сотрудничеству.",
        "cta_resume": "Написать",
        "period_present": "Настоящее время",
        "document": "Документ",
        "admin_title": "Администрирование резюме",
        "admin_site": "CV Админ",
        "admin_dashboard": "Панель управления",
        "cv_content_lang": "Язык текста резюме",
        "cv_content_lang_hint": "Поля ниже — только для выбранного языка. Смените язык и нажмите «Сохранить».",
    },
}


def ui_text(key: str) -> str:
    lang = (get_language() or "en")[:2]
    bucket = _TEXTS.get(lang) or _TEXTS["en"]
    return bucket.get(key) or _TEXTS["en"].get(key, key)
